<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="section-title h2 mb-1">Welcome, <?= esc($applicant['first_name'] ?: $applicant['display_name']) ?></h1><p class="text-muted mb-0">Review your recruitment activity and continue your job search.</p></div><a href="<?= site_url('jobs') ?>" class="btn btn-jng px-4"><i class="bi bi-search me-1"></i>Browse open jobs</a></div>
<div class="row g-4">
<div class="col-xl-8"><div class="card h-100"><div class="card-header bg-white border-0 p-4 pb-0"><div class="d-flex justify-content-between align-items-center"><h2 class="h5 fw-bold mb-0">Recent applications</h2><a href="<?= site_url('applications') ?>" class="small">View all</a></div></div><div class="card-body p-4">
<?php if (! $applications): ?><div class="empty-state"><i class="bi bi-file-earmark-person display-4"></i><p class="mt-3">You have no submitted applications.</p><a href="<?= site_url('jobs') ?>" class="btn btn-jng">View open positions</a></div><?php else: ?><div class="vstack gap-3"><?php foreach (array_slice($applications,0,5) as $application): ?><a href="<?= site_url('applications/' . $application['id']) ?>" class="border rounded-3 p-3 text-decoration-none text-body"><div class="d-flex justify-content-between gap-3"><div><strong><?= esc($application['title']) ?></strong><div class="small text-muted"><?= esc($application['job_code'] ?: '') ?></div></div><span class="badge badge-status align-self-start"><?= esc($application['status_name']) ?></span></div><div class="progress mt-3" style="height:6px"><div class="progress-bar" style="width:<?= (int)$application['progress']['percent'] ?>%;background:#0a0147"></div></div></a><?php endforeach; ?></div><?php endif; ?>
</div></div></div>
<div class="col-xl-4"><div class="card h-100"><div class="card-header bg-white border-0 p-4 pb-0"><div class="d-flex justify-content-between align-items-center"><h2 class="h5 fw-bold mb-0">Saved jobs</h2><a href="<?= site_url('saved-jobs') ?>" class="small">View all</a></div></div><div class="card-body p-4">
<?php if (! $savedJobs): ?><div class="empty-state py-4"><i class="bi bi-bookmark-heart display-5"></i><p class="mt-3 mb-0">Save jobs you want to revisit.</p></div><?php else: ?><div class="vstack gap-3"><?php foreach ($savedJobs as $job): ?><a class="border rounded-3 p-3 text-decoration-none text-body" href="<?= site_url('jobs/' . $job['id']) ?>"><strong class="d-block"><?= esc($job['title']) ?></strong><span class="small text-muted"><?= esc($job['location'] ?: $job['company_name'] ?: 'Joy-Nostalg Group') ?></span></a><?php endforeach; ?></div><?php endif; ?>
<a href="<?= site_url('profile') ?>" class="btn btn-outline-jng w-100 mt-4"><i class="bi bi-person-check me-1"></i>Review profile health</a>
</div></div></div>
</div>
<?= $this->endSection() ?>
